const store=require('./cloud-store');
const easyslip=require('../services/easyslip');
const slipok=require('../services/slipok');
const slipcheck=require('../services/slipcheck');
const rdcw=require('../services/rdcw-slip');
const slip2go=require('../services/slip2go');
const PROVIDERS=new Set(['easyslip','slipok','slipcheck','rdcw','slip2go']);
function expected(p){return{expectedReceiverNames:[p.promptpayName,p.bankAccountName].filter(Boolean),expectedReceiverNumbers:[p.slipProvider==='easyslip'?p.promptpayId:'',p.bankAccountNumber].filter(Boolean)}}
async function verify(buffer,amount,file={}){const p=store.payment(),common=expected(p);switch(p.slipProvider){case'easyslip':return easyslip.verifySlip(buffer,amount,file,common.expectedReceiverNumbers,p.easyslipApiKey||undefined);case'slipok':return slipok.verifySlip(buffer,amount,file,{branchId:p.slipokBranchId,apiKey:p.slipokApiKey,...common});case'slipcheck':return slipcheck.verifySlip(buffer,amount,file,{apiKey:p.slipcheckApiKey,endpoint:p.slipcheckEndpoint,...common});case'rdcw':return rdcw.verifySlip(buffer,amount,file,{clientId:p.rdcwClientId,clientSecret:p.rdcwClientSecret,endpoint:p.rdcwEndpoint,...common});case'slip2go':return slip2go.verifySlip(buffer,amount,file,{apiKey:p.slip2goApiKey,endpoint:p.slip2goEndpoint,...common});default:return{checked:false,verified:false,message:'รอแอดมินตรวจสอบ'}}}
async function test(provider,b){provider=String(Array.isArray(provider)?provider.at(-1):provider||'').trim().toLowerCase();if(!PROVIDERS.has(provider))return{ok:false,message:'ผู้ให้บริการไม่ถูกต้อง'};try{if(provider==='easyslip')return easyslip.getAccountInfo(b.easyslipApiKey);if(provider==='slipok')return slipok.testConnection({branchId:b.slipokBranchId,apiKey:b.slipokApiKey});if(provider==='slipcheck')return slipcheck.getAccountInfo(b.slipcheckApiKey,b.slipcheckEndpoint);if(provider==='rdcw')return rdcw.validateCredentials(b.rdcwClientId,b.rdcwClientSecret);return slip2go.checkBalance(b.slip2goApiKey,b.slip2goEndpoint)}catch(e){return{ok:false,message:e.message}}}
function configured(p=store.payment()){if(p.slipProvider==='easyslip')return Boolean(p.easyslipApiKey);if(p.slipProvider==='slipok')return Boolean(p.slipokBranchId&&p.slipokApiKey);if(p.slipProvider==='slipcheck')return Boolean(p.slipcheckApiKey);if(p.slipProvider==='rdcw')return Boolean(p.rdcwClientId&&p.rdcwClientSecret);if(p.slipProvider==='slip2go')return Boolean(p.slip2goApiKey);return false}
module.exports={PROVIDERS,verify,test,configured};
